[package]
name = "scheduler"
version.workspace = true
edition.workspace = true

[dependencies]
common.workspace = true
weather.workspace = true
anyhow.workspace = true
chrono.workspace = true
dotenvy.workspace = true
sqlx.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
