[package]
name = "ai"
version.workspace = true
edition.workspace = true

[dependencies]
common.workspace = true
route.workspace = true
anyhow.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
tracing.workspace = true
uuid.workspace = true
